### ISSUE TITLE
Required Documentation comment in the starting of programs.

### ISSUE THREAD

**Issue by Sid672** [Sid672/Java#6]
Comments need to be added in the header of the program which gives information about the program.
Programs are present in the "Programs" folder.  If the program already contains comments then only change the format of comments. 

Example:
``` java
public class Main {
  public static void main(String[] agrs) {
    
      Integer i = Integer.valueOf("123");
      int a = i + 2;
      System.out.println(a);
      System.out.println(i);
  }
}
```
``` java
/**
  * Program converts the string into an integer.
  * add 2 and print the result.
  */ 

public class Main {
  public static void main(String[] agrs) {
    
      Integer i = Integer.valueOf("123");
      int a = i + 2;
      System.out.println(a);
      System.out.println(i);
  }
}
```
Comments format: 

```java
/**
  * comments here;
  */
```

**Comment by diksharai9** [comment]
hey!
May I help you with this?

**Comment by Sid672** [comment]
@diksharai9, Go ahead! 
You can start from program 11 in the Programs folder.

**Comment by diksharai9** [comment]
> @diksharai9, Go ahead!
> You can start from program 11 in the Programs folder.

thankyou

**Comment by Sid672** [comment]
Now, Modification is required from Program 31 onwards.

**Comment by diksharai9** [comment]
> Now, Modification is required from Program 31 onwards.

okay, I will do that.

**Comment by Sid672** [comment]
Up to program 50 documentation comments is completed.

**Comment by Sid672** [comment]
Modfication are required from Program52.java

**Comment by ritesh-karankal** [comment]
Hey! can I modify the rest of the comments?

**Comment by Sid672** [comment]
@ritesh-karankal go ahead.
Start from program 52 that is present in the directory of the programs.

**Comment by ritesh-karankal** [comment]
@Sid672 I have two questions
do I need to change single-line comments to multi-line comments?
And does spacing of stars matter as other files have different spacing than above mentioned correct format?

**Comment by Sid672** [comment]
@ritesh-karankal 
Yes please convert single-line comments into multiple-line comments.
If you follow the above format it's the most correct way. I know some files have comments that don't follow the same format for such files I will create a new issue after closing this issue.
